#!/bin/bash

if [[ ! -e /etc/proxmox-backup/csrf.key ]]; then
  echo "PROXY: The proxmox-backup is not yet configured!"
  exit 1
fi

while [ ! -S /dev/log ]; do
    sleep 0.2
done

echo "PROXY: Starting..."
exec chpst -u backup:backup /usr/lib/*/proxmox-backup/proxmox-backup-proxy
