global(workDirectory="/var/spool/rsyslog")

module(load="imuxsock" SysSock.Name="/dev/log")

template(name="DockerLogFormat" type="string" string="%timegenerated% %syslogtag%%msg%\n")

*.* action(type="omfile" file="/var/log/proxmox-backup/syslog.log" template="DockerLogFormat")
